# Generated by Django 5.2.7 on 2025-10-29 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(help_text='City or location name', max_length=255)),
                ('country', models.CharField(blank=True, help_text='Country name', max_length=100)),
                ('latitude', models.FloatField(help_text='Latitude coordinate', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(help_text='Longitude coordinate', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('timezone', models.CharField(default='UTC', help_text='Location timezone', max_length=100)),
                ('start_date', models.DateField(help_text='Start date of weather data range')),
                ('end_date', models.DateField(help_text='End date of weather data range')),
                ('weather_data', models.JSONField(blank=True, default=dict, help_text='Stored weather data for the date range')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this request')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['location_name'], name='api_weather_locatio_efc29e_idx'), models.Index(fields=['start_date', 'end_date'], name='api_weather_start_d_61aacd_idx'), models.Index(fields=['-created_at'], name='api_weather_created_9cf8ff_idx')],
            },
        ),
    ]
