# Generated by Django 5.2.6 on 2025-10-31 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='weatherrequest',
            name='api_weather_created_9cf8ff_idx',
        ),
        migrations.AddField(
            model_name='weatherrequest',
            name='user',
            field=models.ForeignKey(default=None, help_text='User who created this weather request', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='weatherrequest',
            index=models.Index(fields=['user', '-created_at'], name='api_weather_user_id_e10ef6_idx'),
        ),
    ]
